version: '3'
services:
    java-app:
        image: josevictorps/privacyjava
        ports:
          - "8080:8080"
        env_file:
          - secrets/spring_secrets.env
        environment:
          spring.cassandra.username: cassandra
          spring.cassandra.contact-points: cassandra
          spring.cassandra.local-datacenter: datacenter1
          spring.cassandra.keyspace-name: test
          spring.elasticsearch.username: elastic
          spring.elasticsearch.uris: http://elasticsearch:9200
        networks:
            - privacy-network
        container_name: java-app
        depends_on:
            cassandra-load-keyspace:
              condition: service_completed_successfully
            elasticsearch:
              condition: service_started
            kibana:
              condition: service_started

    cassandra:
        image: cassandra:latest #docker.io/bitnami/cassandra:latest
        container_name: cassandra
        ports:
            - "9042:9042"
        networks:
            - privacy-network
        restart: always

    cassandra-load-keyspace:
      container_name: cassandra-load-keyspace
      image: cassandra:latest
      depends_on:
        - cassandra
      volumes:
        - ./schema.cql:/schema.cql
      command: /bin/bash -c "sleep 60 && echo loading cassandra keyspace && cqlsh cassandra -f /schema.cql"
      networks:
        - privacy-network

    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
      env_file:
        - secrets/elasticsearch_secrets.env
      environment:
        ELASTIC_USERNAME: elastic
        discovery.type: "single-node"
        ES_JAVA_OPTS: "-Xms2g -Xmx2g"
        xpack.monitoring.enabled: "true"
        xpack.security.enabled: "true"
      networks:
        - privacy-network
      ports:
        - "9200:9200"
        - "9300:9300"

    kibana:
      image: docker.elastic.co/kibana/kibana:7.17.6
      ports:
        - "5601:5601"
      env_file:
        - secrets/kibana_secrets.env
      environment:
        ELASTICSEARCH_URL: http://elasticsearch:9200
        ELASTICSEARCH_USERNAME: elastic
      networks:
        - privacy-network
      depends_on:
        - elasticsearch

networks:
    privacy-network:
        driver: bridge