---
- hosts: aws_ec2
  become: true
  tasks:
    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: latest
        update_cache: true
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Create secrets folder
      file:
        path: /home/ubuntu/secrets
        state: directory
        mode: 0775

    - name: Copy Container Cluster files to server
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: ubuntu
        group: ubuntu
        mode: "{{ item.mode }}"
      loop:
        - { src: '../Docker/docker-compose.yaml', dest: '/home/ubuntu/', mode: '0664' }
        - { src: '../Docker/schema.cql', dest: '/home/ubuntu/', mode: '0664' }
        - { src: '../Docker/secrets/elasticsearch_secrets.env', dest: '/home/ubuntu/secrets', mode: '0400' }
        - { src: '../Docker/secrets/kibana_secrets.env', dest: '/home/ubuntu/secrets', mode: '0400' }
        - { src: '../Docker/secrets/spring_secrets.env', dest: '/home/ubuntu/secrets', mode: '0400' }
        - { src: '../Docker/nonroot.sh', dest: '/home/ubuntu/', mode: '0755' }

    - name: Create Docker group
      group:
        name: docker
        state: present
    - name: Add main user to Docker group
      user:
        name: ubuntu
        groups: docker
        append: yes
    ### DESLIGAR A MAQUINA MANUALMENTE APOS A CONFIGURACAO NON-ROOT DO DOCKER
